DJINNI_URL = "https://djinni.co/jobs/?all-keywords=&any-of-keywords=&exclude-keywords=&primary_keyword=Python"


TECHNOLOGIES = (
    "Python",
    "OOP",
    "SQL",
    "JavaScript",
    "Django",
    "ORM",
    "REST",
    "JavaScript",
    "Flask",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue.js",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "NoSQL",
    "MongoDB",
    "Redis",
    "Git",
    "Docker",
    "AWS",
    "GCP",
    "Microsoft Azure",
    "API",
    "GraphQL",
    "Unit Testing",
    "pytest",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "Nginx",
    "Apache",
    "Authentication",
    "Authorization",
    "SQLAlchemy",
    "Peewee",
    "Beautiful Soup",
    "Scrapy",
    "NumPy",
    "pandas",
    "Matplotlib",
    "Seaborn",
    "scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Kubernetes",
    "Docker Swarm",
    "Celery",
    "RabbitMQ",
    "Scrum",
    "Kanban",
    "ML",
    "SQLAlchemy",
    "FastAPI",
    "JIRA",
    "AsyncIO",
    "PyCharm",
    "Elasticsearch",
)
